name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the world
        run: echo "Hello, world!"
      
      - name: Runner VM
        run: echo "This job is running on a ${{ runner.os }} runner."

      - name: Triggerer
        run: echo "This job was triggered by ${{ github.actor }}."