name: NODE CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  node-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install client dependencies
        working-directory: ./client
        run: npm ci
      - name: Install serevr dependencies
        working-directory: ./server
        run: npm ci
      - name: Linting client
        working-directory: ./client
        run: npm run lint
      - name: Linting server
        working-directory: ./server
        run: npm run lint
      - name: Build test client
        working-directory: ./client
        run: npm run build