name: NODE CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.build_version.outputs.value }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./client
        run: npm ci

      - name: Linting
        working-directory: ./client
        run: npm run lint
        
      - name: Building
        working-directory: ./client
        run: npm run build
      
      - name: Set version
        id: build_version
        run: echo "value=1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT
  
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Linting
        working-directory: ./server
        run: npm run lint

  deploy:
    needs: [ frontend, backend ]
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' && github.event_name == 'push' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: echo "Deploying version ${{ needs.frontend.outputs.build_version }} to production..."